name: state-machine-sim
version: 0.1.0.0
github: "L0neGamer/state-machine-sim"
license: BSD3
author: "L0neGamer"
maintainer: "L0neGamer"
copyright: "L0neGamer"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/L0neGamer/state-machine-sim#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - vector
  - extra
  - safe

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - RecordWildCards
    - InstanceSigs
    - RecordWildCards
    - MultiParamTypeClasses
    - TupleSections
    - ViewPatterns
    - FlexibleContexts
    - StandaloneDeriving
    - TypeOperators
    - FlexibleInstances
    - RankNTypes
    - TypeApplications
    - MultiWayIf
  ghc-options:
    - -Wall

executables:
  state-machine-sim-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - state-machine-sim

tests:
  state-machine-sim-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - state-machine-sim
